# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- master

variables:
  vmImageName: 'vs2017-win2016'

jobs:
- job: build
  displayName: Build
  pool:
    vmImage: $(vmImageName)

  steps:
  - script: |
      dir
    displayName: 'Print file list'

  - script: |
      echo Building project ...
      echo Build project done!
    displayName: 'Build project'

  - script: |
      echo Running unit test ...
      echo Unit test done!
    displayName: 'Run unit test'
